version: '3.7'

services:
    web:
        build: .
        command: gunicorn main.wsgi -b 0.0.0.0:8000 --log-level DEBUG
        env_file:
            - .env
        volumes:
            - ./backend:/code
            - static_volume:/code/staticfiles
            - media_volume:/code/media
        restart: unless-stopped
        ports:
            - "8000:8000"
            - "4000:4000"
        depends_on:
            - db
        networks:
            - main

    db:
        image: postgres:13.2-alpine
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        restart: unless-stopped
        networks:
            - main

    nginx:
        build:
            context: ./nginx
            dockerfile: dev/Dockerfile
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/dev/dev.conf:/etc/nginx/nginx.conf:ro
            - static_volume:/usr/src/app/staticfiles
            - media_volume:/usr/src/app/media
        depends_on:
            - web
        networks:
            - main
            
networks:
    main:
        driver: bridge

volumes:
    postgres_data:
    static_volume:
    media_volume:

