version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - "${WEB_IMAGE}"
    image: "${WEB_IMAGE}"
    command: gunicorn main.wsgi:application --workers 3 -b 0.0.0.0:8000 --log-level DEBUG
    env_file: .env
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    ports:
      - "8000:8000"
      - "4000:4000"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - main

  db:
    image: postgres:13.2-alpine
    environment:
        POSTGRES_PASSWORD: postgres
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped
    networks:
        - main

  nginx:
    build:
      context: ./nginx
      dockerfile: prod/Dockerfile
      cache_from:
        - "${NGINX_IMAGE}"
    image: "${NGINX_IMAGE}"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    networks:
      - main
    depends_on:
      - web

networks:
  main:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  postgres_data:
