# Generated by Django 3.2.9 on 2021-11-28 11:43

from django.db import migrations, models
import django.db.models.deletion
import places.utils


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20210327_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=places.utils.place_image_path)),
                ('thumbnail', models.ImageField(null=True, upload_to=places.utils.place_thumbnail_path)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place')),
            ],
        ),
    ]
