# Generated by Django 3.1.6 on 2021-03-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address1',
            field=models.CharField(max_length=200, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='place',
            name='address2',
            field=models.CharField(max_length=200, verbose_name='Address line 2'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(),
        ),
    ]
