# Generated by Django 3.2.9 on 2021-12-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_placeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
